// Generated by @adddog/monorepo-consistency
// Do not edit manually - regenerate with: pnpm generate:knip
import { defineKnipConfig } from "@adddog/monorepo-consistency";

export default defineKnipConfig({
    entry: ["src/index.ts"],
    project: ["src/**/*.ts"],
    // WHY: referenced via /// <reference types="dom-webcodecs" /> in media.d.ts
    ignoreDependencies: ["dom-webcodecs"],
});
