// Generated by monorepo-scripts/generate-knip-config.mts
// Do not edit manually - regenerate with: pnpm generate:knip
import { defineKnipConfig } from "../../monorepo-scripts/knip-defaults.js";

export default defineKnipConfig({
    entry: ["src/index.ts"],
    project: ["src/**/*.ts"],
    ignoreDependencies: ["dom-webcodecs"],
});
